version: "3.8"

volumes:
  go_api_db:

services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - go_api_db:/bitnami/mariadb
    environment:
      MARIADB_ROOT_USER: user
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: api
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MARIADB_ROOT_USER --password=$$MARIADB_ROOT_PASSWORD
      interval: 5s
      retries: 5

  app:
    build: .
    image: go-api:latest
    restart: on-failure
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - DB_CONNECTION=user:pass@tcp(mariadb:3306)/api?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      mariadb:
        condition: service_healthy
