version: "3.8"

volumes:
  go_api_db:
  go_api_redis:

services:
  mariadb:
    image: bitnami/mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - go_api_db:/bitnami/mariadb
    environment:
      MARIADB_ROOT_USER: user
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: api
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MARIADB_ROOT_USER --password=$$MARIADB_ROOT_PASSWORD
      interval: 3s
      retries: 5

  redis:
    image: bitnami/redis:7.0.5
    restart: always
    ports:
      - "6375:6379"
    volumes:
      - go_api_redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: pass
      REDIS_DISABLE_COMMANDS: FLUSHALL,CONFIG
    healthcheck:
      test: redis-cli --no-auth-warning --pass pass ping | grep PONG
      interval: 3s
      retries: 5

  app:
    build: .
    image: go-api:latest
    restart: on-failure
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      DB_CONNECTION: user:pass@tcp(mariadb:3306)/api?charset=utf8mb4&parseTime=True&loc=Local
      REDIS_CONNECTION: redis://:pass@redis:6379/0
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
